### ISSUE TITLE
cart.phpで「買い物を続ける」を押したときの処理

### ISSUE THREAD

**Issue by fukuchancat** [B7-OBookStore/WebSystem#10]
元のページに戻れるようにするか、あるいはこのリンク自体を消してしまうか。たすけて

**Comment by rindoussn** [comment]
まかせろ〜ﾊﾞﾘﾊﾞﾘ~

**Comment by rindoussn** [comment]
Commit ea6167c にて修正済みです。
Cart.phpで「買い物を続ける」を押した時、最後に検索したものを表示するように修正しました。
