### ISSUE TITLE
registration_check.phpの表示崩れ

### ISSUE THREAD

**Issue by rindoussn** [B7-OBookStore/WebSystem#2]
registration_check.phpの表示崩れうまくなおせませんでした・・・
時間があるときに修正していただけるとありがたいです〜
![screenshot_20170122_172452](https://cloud.githubusercontent.com/assets/20217085/22181121/17bfacf4-e0c8-11e6-9213-2443fea9551c.png)

**Comment by fukuchancat** [comment]
Commit 325768a にて修正完了しましたにゃーん
