### ISSUE TITLE
book.phpでページを表示できないバグ

### ISSUE THREAD

**Issue by rindoussn** [B7-OBookStore/WebSystem#24]
検索で「あいうえお」と検索して幾つかの本をクリックしてみたところ、
画面が真っ白になってページが表示できないバグが再現しました。
今のところ原因は不明です。

**Comment by fukuchancat** [comment]
@rindoussn 「あいうえお」で上から80件の検索結果を表示しましたがこちらでは再現できませんでした。バグが出るのはどの本かわかりますか？

**Comment by rindoussn** [comment]
上から20件はすべて動きませんでした＋白井先生の本以外は全部アウトでした。サーバー関係のバグの可能性もありそうなのでそっちもチェックしてから再度報告します。

**Comment by rindoussn** [comment]
原因判明しました。サーバーサイドの問題でした。申し訳ないです。
php-gettextで使われている関数が存在せずひっかかっていたようです。
拡張モジュールなのでWebMatrixでは自動でそこらへん設定してくれてたのかな…
前のUbuntu 16.04 LTSでは勝手に入れられてたっぽいですね。
Azure / AWS等にデプロイするときにも問題になりそうな気がするのでメモ書きとして残しておきます。
