### ISSUE TITLE
会員登録に「2月31日」などありえない日付を入力できる

### ISSUE THREAD

**Issue by fukuchancat** [B7-OBookStore/WebSystem#7]
registered.phpで会員登録そのものには失敗するが、元々入力できないようにするのがﾕｳｻﾞﾋﾞﾘﾃｨｲってものだぜ
![image](https://cloud.githubusercontent.com/assets/19220989/22192603/b4dc1422-e178-11e6-8719-b7f4771505dd.png)

**Comment by rindoussn** [comment]
Commit 092c244 にて修正済み。
